; Configurazione Clipass
; Usa \n per inserire ritorni a capo nei valori.

[General]
Hotkey=Ctrl+Shift+Space ; non funzionante al momento
StartHidden=false
AutoClose=true
AutoPaste=false ; può essere true solo se AutoClose è true

[Window]
Width=400
Height=300
Margin=4
TextBoxMargin=6

[Item:email]
Value=nome.cognome@example.com

[Item:telefono]
Value=+39 333 1234567
Hidden=false

[Item:firma]
Value=Cordiali saluti,\nMario Rossi
Hidden=false

[Item:secret]
Value=mysecret
Hidden=true
